CC          = g++

CFLAGS      = -I.                         \
              -fPIC                       \
              `freetype-config --cflags`  \
              `sdl-config --cflags`       \
              -Wall
            
LDFLAGS     = `freetype-config --libs` \
              `sdl-config --libs` \
              -lSDL \
              -lSDLmain \
              -lSDL_net \
              -lSDL_gfx
            
OBJFILES   := $(patsubst %.cpp,%.o,$(wildcard ./src/*.cpp))
BINARY      = libgp2d.so
INSTALL_DIR = /usr

all: gp2d

gp2d: $(OBJFILES)
	@echo "=== Linking: $(OBJFILES) -> $(BINARY)"
	@$(CC) -shared $(LDFLAGS) -o bin/$(BINARY) $(OBJFILES)

clean:
	@echo "=== Deleting $(OBJFILES)"
	@rm $(OBJFILES) -v
	@echo "=== Deleting bin/$(BINARY)"
	@rm bin/$(BINARY) -v

install:
	@echo "=== Installing: bin/$(BINARY) -> $(INSTALL_DIR) ..."
	@mkdir $(INSTALL_DIR)/include/gp2d
	@cp bin/$(BINARY) $(INSTALL_DIR)/lib -v
	@cp src/*.h $(INSTALL_DIR)/include/gp2d -v

uninstall:
	@echo "=== Uninstalling: $(INSTALL_DIR)/$(BINARY) ..."
	@rm $(INSTALL_DIR)/lib/$(BINARY) -v; rm $(INSTALL_DIR)/include/gp2d -r -v

%.o: %.cpp
	@echo "=== Compiling: $< -> $@"
	$(CC) $(CFLAGS) -c -o $@ $<
